name: reduceo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animated_splash_screen: ^1.2.0
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.4
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/profile.svg
    - assets/wave.png
    - assets/login.svg
fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter-Regular.ttf
        weight: 400
